server:
  port: 8081

spring:
  application:
    name: credit-assessment-service
  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:true}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:loanRedisPassword}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: credit-assessment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "bank.pf.*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      loan-application-received: LoanApplicationReceivedEventTopic
      credit-assessment-completed: CreditAssessmentCompletedEventTopic
  external-services:
    bureau-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:8089}/bureau/score
    antifraud-url: http://${WIREMOCK_HOST:localhost}:${WIREMOCK_PORT:8089}/antifraud/check

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,loggers,metrics,beans,env,configprops
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
    sender:
      type: web
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    bank.pf: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} %highlight(%5p) %clr([%X{traceId:-0},%X{spanId:-0}]){green} %clr([%t]){magenta} %clr(%c{1}){cyan} - %m%n"
