server:
  port: 8082

spring:
  application:
    name: loan-decision-engine
  threads:
    virtual:
      enabled: ${SPRING_THREADS_VIRTUAL_ENABLED:true}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: loan-decision-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "bank.pf.*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topics:
      credit-assessment-completed: CreditAssessmentCompletedEventTopic
      loan-decision-made: LoanDecisionMadeEventTopic
  loan-application-service:
    url: ${LOAN_APPLICATION_SERVICE_URL:http://localhost:8080}
    update-status-uri: "/api/v1/loans/internal/{applicationId}/status"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,loggers,metrics,beans,env,configprops
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:1.0}
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}
    sender:
      type: web
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    root: INFO
    bank.pf: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} %highlight(%5p) %clr([%X{traceId:-0},%X{spanId:-0}]){green} %clr([%t]){magenta} %clr(%c{1}){cyan} - %m%n"