package bank.pf.enums;

public enum LoanStatus {

    PENDING_VALIDATION,
    PENDING_ASSESSMENT,
    UNDER_MANUAL_REVIEW,
    PENDING_MANUAL_REVIEW,
    APPROVED,
    REJECTED,
    CONTRACT_PENDING,
    ACTIVE,
    PAID_OFF,
    EVENT_PUBLISHING_FAILED,
    DEFAULTED
}
